# -----------------------------
# Kubernetes Secret for DB creds
# -----------------------------
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-secret
type: Opaque
data:
  # Base64 encode your values
  DB_USER: ZmVsaXg=      # felix
  DB_PASSWORD: Z2Vud29yeA==      # genworx
  DB_NAME: ZWNvbW1lcmNl          # ecommerce

---
# -----------------------------
# Deployment
# -----------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-demo
  template:
    metadata:
      labels:
        app: gke-demo
    spec:
      containers:
        - name: app
          image: us-west1-docker.pkg.dev/active-valve-479215-b4/my-docker-art/gek-demo:v4
          ports:
            - containerPort: 8001
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-secret
                  key: DB_NAME
            - name: DB_HOST
              value: "<CLOUDSQL_PRIVATE_IP_OR_SERVICE>"  # replace with your Cloud SQL IP/service
            - name: DB_PORT
              value: "5432"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
# -----------------------------
# Service (LoadBalancer)
# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: gke-demo-svc
spec:
  type: LoadBalancer
  selector:
    app: gke-demo
  ports:
    - port: 8001
      targetPort: 8001
