apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:genworx@postgres-service:5432/ecommerce"
  SECRET_KEY: "replace-this-with-a-strong-key"
